CREATE TABLE IF NOT EXISTS user (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR (50) NOT NULL,
email VARCHAR (100) NOT NULL,
password VARCHAR(100) NOT NULL,
user_role INT NOT NULL,
FOREIGN KEY (user_role) REFERENCES user_role(id));